### ISSUE TITLE
PHP error_log configuration is missing

### ISSUE THREAD

**Issue by mxr576** [uselagoon/lagoon-images#662] opened 2023-01-18 09:29 UTC
`error_log` configuration is not set in PHP images. It should be set to  `/proc/self/fd/2` like [in the official PHP image](https://github.com/docker-library/php/blob/55fb15102c30235106e36e07f5eb447d54d16d27/8.1/buster/fpm/Dockerfile#L244-L257).
This is basically the default configuration for 12fa PHP application.

**Comment by rocketeerbkw** [comment] 2023-01-18 21:52
I was doing some research around this and I'm seeing conflicting information. I see issues saying this needs to be added in order for docker to get error logs, but also  some issues (admittedly old ones) are saying this won't work for php-fpm because of child process log mixing.

It would be helpful to get some more information so I don't waste time looking at outdated info. Is something not working that making this change would fix? Do you have any other background on why it should be added other than the upstream image has it?

**Comment by mxr576** [comment] 2023-01-19 09:56
This is the most extensive guide that I have found related to this topic: https://rtfm.co.ua/en/linux-php-fpm-docker-stdout-and-stderr-no-an-applications-error-logs/

This comment is also fairly detailed about related configuration bits: https://github.com/docker-library/php/issues/878#issuecomment-938595965

> but also some issues (admittedly old ones) are saying this won't work for php-fpm because of child process log mixing.

Maybe you have read this in GH issues or in the Stackoverflow post but it looks like all problems have been solved around these with PHP 8.0 (with `decorate_workers_output = no`) and `catch_workers_output = yes`. 

My ultimate goal with this change is to see fatal errors at least in container logs on Kibana when the application crashes and not even Monolog was booted that could have distributed log messages to Logtash or other places. 

And for the record, what triggered this change request is that Monolog failed to send a log to Logstash due to some networking issues therefore it got tracked nowhere... So even if Monolog is working, other issues (like I/O, and networking) could happen but we cannot lose logs. So my idea is using setting up `error_log()` as an exception handler in Monolog (see related [PR](https://github.com/Seldaek/monolog/pull/1012/files#diff-1e7fd545cec457de) to ensure logs are caught and available in Kibana (via container logs) even if Logstash connection failed. (Not to mention after this change, we could also see if a Monolog handler regularly fails to track logs.)

**Comment by mxr576** [comment] 2023-01-19 11:45
In addition, Symfony's logging doc also says:

> In the prod environment, logs are written to [STDERR PHP stream](https://www.php.net/manual/en/features.commandline.io-streams.php), which works best in modern containerized applications deployed to servers without disk write permissions.

https://symfony.com/doc/current/logging.html#where-logs-are-stored

**Comment by rocketeerbkw** [comment] 2023-03-20 15:23
I had some time to look into this some more. It looks to me that everything is already configured correctly? When I test our images with php code that throws errors, everything is getting logged correctly for a docker architecture.

I also checkout our upstream images and it's already being set as you suggested https://github.com/docker-library/php/blob/9e9fd53ae5107ce1904e9bb6b428b93b9519037c/8.2/alpine3.16/fpm/Dockerfile#L230.

Are there specific error that you aren't seeing in the logs? Can you provide a reproducible test?

**Comment by rocketeerbkw** [comment] 2023-04-24 19:50
@mxr576 do you have any more info on this? I'll close it as not reproducible if not.

**Comment by rocketeerbkw** [comment] 2023-05-25 21:39
We think this is working as expected.

**Closed by rocketeerbkw** 2023-05-25 21:39 UTC
