### ISSUE TITLE
Dynamic PHP error reporting settings are not taking effect

### ISSUE THREAD

**Issue by GROwen** [uselagoon/lagoon-images#322] opened 2021-10-14 10:25 UTC
The behaviour described in the Lagoon docs for the [special environment variable PHP_ERROR_REPORTING](https://docs.lagoon.sh/lagoon/using-lagoon-advanced/environment-variables#php_error_reporting) states that

>On production environments, this value defaults to E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE.
>On development environments, this value defaults to E_ALL & ~E_DEPRECATED & ~E_STRICT.

However all environments have the same setting. 

### Steps to reproduce
Deploy a project to production and development environments

### Expected behaviour
>On production environments, this value defaults to E_ALL & ~E_DEPRECATED & ~E_STRICT & ~E_NOTICE.
>On development environments, this value defaults to E_ALL & ~E_DEPRECATED & ~E_STRICT.

### Actual behaviour
>On all environments this value defaults to E_ALL & ~E_DEPRECATED & ~E_STRICT.

@tobybellwood Has already fixed this by updating the [entrypoints](https://github.com/uselagoon/lagoon-images/blob/arm64_images/images/php-fpm/7.4.Dockerfile#L39) in #320. That can just be ported here :)

**Comment by christopher-hopper** [comment] 2022-01-18 04:24
Did this get fixed with the merge of #323 on 20 Oct 2021?

**Comment by tobybellwood** [comment] 2022-01-18 04:43
IIRC this was caused by one of the entrypoints (51-production-detection.sh) being missed in the dockerfile - the dockerfile now includes all entrypoints by default.

Are you seeing something different @christopher-hopper?

**Comment by tobybellwood** [comment] 2022-01-18 04:52
I checked with
```
tobybellwood@pop-os:~/sites  $ docker run --rm -it uselagoon/php-7.4-fpm php -r 'echo error_reporting();'
22527
tobybellwood@pop-os:~/sites  $ docker run -e LAGOON_ENVIRONMENT_TYPE=production --rm -it uselagoon/php-7.4-fpm php -r 'echo error_reporting();'
22519
```
Integer value is calculated from https://www.php.net/manual/en/errorfunc.constants.php
i.e. 
32767-8192-2048-8=22519 (i.e. ~E_NOTICE is set on prod)
32767-8192-2048=22527 (i.e. ~E_NOTICE is not set in dev)

**Comment by christopher-hopper** [comment] 2022-01-18 23:21
Thanks @tobybellwood I haven't seen anything different. I just wanted to double-check before attempting to pull down updated images and redeploying our PHP application. 

This means then that we can close this issue as fixed right @GROwen ?

**Closed** 2023-05-25 21:47 UTC
